spring:
  application:
    name: Bookcentric
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
  datasource:
    url: ${BOOKCENTRIC_JDBC_DATASOURCE_URL}
    username: ${BOOKCENTRIC_JDBC_DATASOURCE_USERNAME}
    password: ${BOOKCENTRIC_JDBC_DATASOURCE_PASSWORD}
  profiles:
    active:
    - ${BOOKCENTRIC_PROFILE_ACTIVE}
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${BOOKCENTRIC_EMAIL_USER}
    password: ${BOOKCENTRIC_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level: 
    com.bookcentric: DEBUG
  file: bookcentric.log

server:
  port: 50000
  
app:
  email-recipient: ${BOOKCENTRIC_APP_EMAIL_RECIPIENT}