spring:
  application:
    name: Bookcentric
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/bookcentric
    username: root
    password: ${BOOKCENTRIC_JDBC_DATASOURCE_PASSWORD}
  profiles:
    active:
    - ${BOOKCENTRIC_APP_PROFILE_ACTIVE}
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: noreply.bookcentric@gmail.com
    password: bookcentric2019
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level: 
    com.bookcentric: DEBUG
  file: bookcentric.log

server:
  port: 50000